name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

# 顶层权限（写权限必需）
permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  id-token: write

jobs:
  claude:
    # 含 @claude 的评论 / review 评论 / PR review / issue 标题或正文
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest

    # job 级权限（冗余但清晰）
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      id-token: write

    steps:
      # 1) 用 PAT 检出代码，确保后续能创建分支、提交、推送
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GH_PAT }}

      # 2) 配置 git 身份
      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3) 先验证 Anthropic API Key 是否可用（必须返回 HTTP 200 才继续）
      - name: Verify Anthropic API key works
        env:
          KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          set -e
          echo "Pinging Anthropic /v1/models ..."
          CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "x-api-key: $KEY" \
            -H "anthropic-version: 2023-06-01" \
            https://api.anthropic.com/v1/models)
          echo "HTTP $CODE"
          test "$CODE" = "200"

      # 4) 运行 Claude Code（显式指定模型；使用 GH_PAT 和 ANTHROPIC_API_KEY）
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.GH_PAT }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # 显式指定模型（你账号一定有 quota 的版本）
          model: "claude-3-5-sonnet-20240620"

          # 允许 Claude 使用这些工具（写文件 + git 全流程）
          allowed_tools: |
            Write(*)
            Edit(*)
            Bash(git status)
            Bash(git add -A)
            Bash(git commit -m *)
            Bash(git push origin *)
            Bash(ls -la)
            Bash(pwd)

          # 给它多一点交互和时间
          max_turns: 20
          timeout_minutes: 20

          # 读取 CI 结果（保留）
          additional_permissions: |
            actions: read

          # 触发设置（保留）
          trigger_phrase: "@claude"
          label_trigger: "claude"
          branch_prefix: "claude/"
          mode: tag
